### ISSUE TITLE
permission denied, mkdir '/root/.tonlabs/binaries/0_22_0'

### ISSUE THREAD

**Issue by MrSyabro** [tonlabs/ton-dev-cli#21]
I installed NodeJS on Fedora 32 and issued the command `sudo npm install -g ton-dev-cli`, downloading all the dependencies, I got this error:
```
sh: builderror.log: Отказано в доступе

> ton-client-node-js@0.22.0 install /usr/local/lib/node_modules/ton-dev-cli/node_modules/ton-client-node-js
> node install.js

Error: EACCES: permission denied, mkdir '/root/.tonlabs/binaries/0_22_0'
    at Object.mkdirSync (fs.js:841:3)
    at main (/usr/local/lib/node_modules/ton-dev-cli/node_modules/ton-client-node-js/install.js:101:16)
    at /usr/local/lib/node_modules/ton-dev-cli/node_modules/ton-client-node-js/install.js:113:15
    at Object.<anonymous> (/usr/local/lib/node_modules/ton-dev-cli/node_modules/ton-client-node-js/install.js:118:3)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {
  errno: -13,
  syscall: 'mkdir',
  code: 'EACCES',
  path: '/root/.tonlabs/binaries/0_22_0'
}

**Comment by melsomino** [comment]
Preferred way is to fix your `npm` environment instead of running `npm install` under `sudo`.

Read this official npm instructions: https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally

You must have ability to install global npm packages without `sudo`.
